
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kpfrojdpkfjyazgcznko.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtwZnJvamRwa2ZqeWF6Z2N6bmtvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE1OTQxNjUsImV4cCI6MjA1NzE3MDE2NX0.2CjS2cNtR0Z-WJhBeSSUqEk4xtHNJizDyNeZ6XTYi08";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Utility function to format dates for Supabase
export const formatDateForSupabase = (date: Date): string => {
  return date.toISOString().split('T')[0]; // Format as YYYY-MM-DD
};
